### ISSUE TITLE
  build error--Manually-specified variables were not used by the project

### ISSUE THREAD

**Issue by bahramii** [MOCAP4ROS2-Project/mocap_interfaces#2]
hi, 

on ros2 humble I faced this message:

    --- stderr: mocap_interfaces                                
    CMake Warning:
    Manually-specified variables were not used by the project:

    CATKIN_INSTALL_INTO_PREFIX_ROOT
    CATKIN_SYMLINK_INSTALL

however wih uncommenting this part:

    

on package.xml, the issue is solved.

**Comment by aaggj** [comment]
Hi! thank you for your comment, I have modified to remove the warning.

Best.
